import { requireUser, verifyPassword } from "@/server/auth.js";
import { ensureUserData, readState } from "@/server/store.js";
import { updateState } from "@/server/store.js";
import { clearSessionCookie } from "@/server/auth.js";
import { requireSameOrigin } from "@/server/security.js";
import { deleteMedia } from "@/server/storage.js";
export const runtime = "nodejs";
export async function GET(request: Request) { const state = await readState(); const session = requireUser(state, request); if (!session) return Response.json({ error: "יש להתחבר" }, { status: 401 }); const user = state.users.find((item) => item.id === session.userId); const data = ensureUserData(state, session.userId); const payload = { exportedAt: new Date().toISOString(), product: "CALOREAZI", user: { id: user.id, name: user.name, email: user.email }, profile: data.profile, today: data.today, history: data.history, measurements: data.measurements, activity: data.activity, favorites: data.favorites, foodCalibration: data.foodCalibration, coachHistory: data.coachHistory, partnerships: state.partnerships.filter((item) => item.ownerId === session.userId || item.partnerId === session.userId), trash: state.trash.filter((item) => item.userId === session.userId), analysisJobs: state.analysisJobs.filter((item) => item.userId === session.userId) }; return new Response(JSON.stringify(payload, null, 2), { headers: { "Content-Type": "application/json", "Content-Disposition": `attachment; filename="caloreazi-${new Date().toISOString().slice(0, 10)}.json"` } }); }

export async function DELETE(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const state = await readState(); const session = requireUser(state, request); if (!session) return Response.json({ error: "יש להתחבר" }, { status: 401 }); const body = await request.json(); if (body.confirmation !== "DELETE MY DATA") return Response.json({ error: "נדרש אישור מפורש למחיקת הנתונים" }, { status: 400 }); const user = state.users.find((item) => item.id === session.userId); if (!user || !(await verifyPassword(String(body.password || ""), user.password))) return Response.json({ error: "הסיסמה הנוכחית שגויה — החשבון לא נמחק" }, { status: 400 }); const data = ensureUserData(state, session.userId); const media = [...data.history, data.today].flatMap((day) => day.meals || []).map((meal) => meal.media).filter(Boolean); for (const item of media) await deleteMedia(state, item); await updateState((latest) => { latest.users = latest.users.filter((item) => item.id !== session.userId); delete latest.userData[session.userId]; latest.sessions = latest.sessions.filter((item) => item.userId !== session.userId); latest.partnerships = latest.partnerships.filter((item) => item.ownerId !== session.userId && item.partnerId !== session.userId); latest.trash = latest.trash.filter((item) => item.userId !== session.userId); latest.analysisJobs = latest.analysisJobs.filter((item) => item.userId !== session.userId); latest.foodCatalog = latest.foodCatalog.filter((item) => item.ownerId !== session.userId); return latest; }); return Response.json({ ok: true, deleted: true, backupPolicy: "Existing administrator or Home Assistant backups expire according to their configured retention policy." }, { headers: { "Set-Cookie": clearSessionCookie(request) } }); }
