import { requireUser } from "@/server/auth.js";
import { ensureUserData, readState, updateState, userView } from "@/server/store.js";
import { entryDateFor } from "@/server/local-date.js";
import { beverageNutrition, hydrationBeverage, hydrationContribution, hydrationTotal, normalizeCustomBeverage } from "@/server/hydration.js";
export const runtime = "nodejs";
export async function POST(request: Request) {
  const initial = await readState();
  const session = requireUser(initial, request);
  if (!session) return Response.json({ error: "יש להתחבר" }, { status: 401 });
  const mutationKey = String(request.headers.get("idempotency-key") || "").slice(0, 120); const receipt = `${session.userId}:water:post:${mutationKey}`;
  if (mutationKey && (initial.systemSettings?.mutationReceipts || []).includes(receipt)) return Response.json(userView(initial, session.userId, session.role === "admin"));
  const { amount = 250, recordedAt, localDate, beverageId = "water" } = await request.json(); const eventTime = Number.isFinite(Date.parse(String(recordedAt || ""))) ? new Date(recordedAt).toISOString() : new Date().toISOString();
  const state = await updateState((latest) => { const data = ensureUserData(latest, session.userId); const custom = data.profile.customHydrationBeverages || []; const beverage = hydrationBeverage(String(beverageId), custom); const eventDate = /^\d{4}-\d{2}-\d{2}$/.test(String(localDate || "")) ? String(localDate) : entryDateFor(data, eventTime); let day = data.today.date === eventDate ? data.today : data.history.find((item) => item.date === eventDate); if (!day) { day = { date: eventDate, waterMl: 0, waterEvents: [], meals: [] }; data.history.push(day); data.history.sort((a, b) => a.date.localeCompare(b.date)); } const delta = Math.round(Number(amount || 0)); day.waterEvents = Array.isArray(day.waterEvents) ? day.waterEvents : []; day.meals = Array.isArray(day.meals) ? day.meals : []; if (delta > 0) { const eventId = crypto.randomUUID(); const nutrition = beverageNutrition(delta, beverage.id, custom); const mealId = nutrition.kcal > 0 ? crypto.randomUUID() : null; day.waterEvents.push({ id: eventId, amount: delta, hydrationMl: hydrationContribution(delta, beverage.id, custom), beverageId: beverage.id, beverageName: beverage.name, icon: beverage.icon, ...(mealId ? { mealId } : {}), time: eventTime }); if (mealId) day.meals.push({ id: mealId, hydrationEventId: eventId, beverageEntry: true, name: beverage.name, period: "snack", ...nutrition, sugar: 0, items: [{ name: beverage.name, grams: delta, quantity: 1, kcalPer100: beverage.kcalPer100, proteinPer100: beverage.proteinPer100, carbsPer100: beverage.carbsPer100, fatPer100: beverage.fatPer100, nutritionSource: { sourceId: `hydration:${beverage.id}`, source: "CALOREAZI beverage reference" } }], source: "manual", confidence: .9, time: eventTime, logicalDate: eventDate }); } else if (delta < 0) { let remaining = Math.abs(delta); for (let index = day.waterEvents.length - 1; index >= 0 && remaining > 0; index -= 1) { const event = day.waterEvents[index]; if ((event.beverageId || "water") !== beverage.id) continue; const eventAmount = Number(event.amount || 0); if (eventAmount <= remaining) { remaining -= eventAmount; day.waterEvents.splice(index, 1); if (event.mealId) day.meals = day.meals.filter((meal) => meal.id !== event.mealId); } else { const nextAmount = eventAmount - remaining; day.waterEvents[index] = { ...event, amount: nextAmount, hydrationMl: hydrationContribution(nextAmount, beverage.id, custom) }; if (event.mealId) { const nutrition = beverageNutrition(nextAmount, beverage.id, custom); day.meals = day.meals.map((meal) => meal.id === event.mealId ? { ...meal, ...nutrition, items: (meal.items || []).map((item) => ({ ...item, grams: nextAmount })) } : meal); } remaining = 0; } } } day.meals.sort((a, b) => String(a.time).localeCompare(String(b.time))); day.waterMl = hydrationTotal(day.waterEvents); if (mutationKey) { latest.systemSettings.mutationReceipts = [...(latest.systemSettings.mutationReceipts || []), receipt].slice(-2000); } return latest; });
  return Response.json(userView(state, session.userId, session.role === "admin"));
}
export async function PUT(request: Request) {
  const initial = await readState(); const session = requireUser(initial, request);
  if (!session) return Response.json({ error: "יש להתחבר" }, { status: 401 });
  const { amount, targetWaterMl, localDate, beverages, customBeverages } = await request.json(); const waterMl = Math.max(0, Math.min(20_000, Math.round(Number(amount) || 0))); const dailyTarget = Math.max(1500, Math.min(2750, Math.round(Number(targetWaterMl) || 2000)));
  const state = await updateState((latest) => { const data = ensureUserData(latest, session.userId); const editDate = /^\d{4}-\d{2}-\d{2}$/.test(String(localDate || "")) ? String(localDate) : data.today.date; const day = data.today.date === editDate ? data.today : data.history.find((item) => item.date === editDate); if (day) { day.waterMl = waterMl; day.waterEvents = Array.isArray(day.waterEvents) ? day.waterEvents : []; } data.profile.waterMl = dailyTarget; if (Array.isArray(customBeverages)) data.profile.customHydrationBeverages = customBeverages.slice(0, 10).map(normalizeCustomBeverage).filter((item) => item.name); const custom = data.profile.customHydrationBeverages || []; if (Array.isArray(beverages)) data.profile.hydrationBeverages = [...new Set(beverages.map(String).filter((id) => id !== "water" && hydrationBeverage(id, custom).id === id))].slice(0, 18); return latest; });
  return Response.json(userView(state, session.userId, session.role === "admin"));
}
