import { createHash } from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { readFile, readdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";
import { currentSession, requireAdmin } from "@/server/auth.js";
import { requireSameOrigin } from "@/server/security.js";
import { probeStorage } from "@/server/storage.js";
import { addAudit, readState, updateState, writeState } from "@/server/store.js";
export const runtime = "nodejs";

const FORMAT = "caloreazi-backup-v2";
function digest(value: string | Uint8Array) { return createHash("sha256").update(value).digest("hex"); }
async function backupDir(state: unknown) { return (await probeStorage(state, "backup")).resolved; }
function configurationFrom(state: any) { return { version: state.version, ai: state.ai, systemSettings: state.systemSettings }; }
function createArchive(state: any, type: string) { const payload = type === "configuration" ? configurationFrom(state) : state; const serialized = JSON.stringify(payload); return { format: FORMAT, type, createdAt: new Date().toISOString(), schemaVersion: state.version, payloadSha256: digest(serialized), payload }; }
function readArchive(data: Uint8Array) { const archive = JSON.parse(gunzipSync(data).toString("utf8")); if (archive.format !== FORMAT || !["database", "configuration", "full", "safety"].includes(archive.type)) throw new Error("פורמט הגיבוי אינו נתמך"); if (digest(JSON.stringify(archive.payload)) !== archive.payloadSha256) throw new Error("בדיקת השלמות של הגיבוי נכשלה"); return archive; }
async function inspectBackup(dir: string, name: string) { const file = path.join(dir, name); const info = await stat(file); try { const data = await readFile(file); const archive = readArchive(data); return { name, size: info.size, createdAt: archive.createdAt || info.mtime.toISOString(), type: archive.type, verified: true, sha256: digest(data) }; } catch (error) { return { name, size: info.size, createdAt: info.mtime.toISOString(), type: "unknown", verified: false, error: error instanceof Error ? error.message : "invalid" }; } }
async function listBackups(state: unknown) { const dir = await backupDir(state); const files = (await readdir(dir)).filter((name) => /^caloreazi-.*\.json\.gz$/.test(name)); return Promise.all(files.map((name) => inspectBackup(dir, name))); }

export async function GET(request: Request) { const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; const requested = new URL(request.url).searchParams.get("download"); if (requested) { const safe = path.basename(requested); if (safe !== requested || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const data = await readFile(path.join(await backupDir(state), safe)); readArchive(data); return new Response(data, { headers: { "Content-Type": "application/gzip", "Content-Disposition": `attachment; filename="${safe}"` } }); } catch { return Response.json({ error: "הגיבוי לא נמצא או אינו תקין" }, { status: 404 }); } } return Response.json({ backups: (await listBackups(state)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), retention: state.systemSettings.backupRetention }); }

export async function POST(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; let body: any = {}; try { body = await request.json(); } catch { /* UI sends no body */ } const type = ["database", "configuration", "full"].includes(body.type) ? body.type : "database"; const dir = await backupDir(state); const name = `caloreazi-${type}-${new Date().toISOString().replace(/[:.]/g, "-")}.json.gz`; const file = path.join(dir, name); await writeFile(file, gzipSync(JSON.stringify(createArchive(state, type))), { mode: 0o600 }); const verified = await inspectBackup(dir, name); if (!verified.verified) { await unlink(file); return Response.json({ error: "הגיבוי נוצר אך בדיקת השלמות נכשלה" }, { status: 500 }); } await updateState((latest) => { addAudit(latest, { userId: currentSession(request)?.userId || null, action: "backup.created", target: name, details: `${type}:${verified.sha256}` }); return latest; }); const backups = (await listBackups(state)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); const keep = Number(state.systemSettings.backupRetention || 14); for (const item of backups.slice(keep)) await unlink(path.join(dir, item.name)); return Response.json({ ok: true, backup: verified, backups: backups.slice(0, keep) }); }

export async function PATCH(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const current = await readState(); const denied = requireAdmin(current, request); if (denied) return denied; const { name } = await request.json(); const safe = path.basename(String(name || "")); if (safe !== name || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const dir = await backupDir(current); const archive = readArchive(await readFile(path.join(dir, safe))); if (archive.type === "configuration") throw new Error("יש לייבא גיבוי הגדרות דרך Import Configuration ולא דרך שחזור מלא"); if (!Array.isArray(archive.payload.users) || !archive.payload.userData || !archive.payload.ai) throw new Error("מבנה הגיבוי אינו תקין"); const safetyName = `caloreazi-safety-${new Date().toISOString().replace(/[:.]/g, "-")}.json.gz`; await writeFile(path.join(dir, safetyName), gzipSync(JSON.stringify(createArchive(current, "safety"))), { mode: 0o600 }); const safety = await inspectBackup(dir, safetyName); if (!safety.verified) throw new Error("Safety Backup לא עבר בדיקת שלמות"); addAudit(archive.payload, { userId: currentSession(request)?.userId || null, action: "backup.restored", target: safe, details: `Safety backup: ${safetyName}` }); await writeState(archive.payload); return Response.json({ ok: true, restored: safe, safetyBackup: safetyName }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "שחזור הגיבוי נכשל" }, { status: 400 }); } }

export async function PUT(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const current = await readState(); const denied = requireAdmin(current, request); if (denied) return denied; const { name } = await request.json(); const safe = path.basename(String(name || "")); if (safe !== name || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const archive = readArchive(await readFile(path.join(await backupDir(current), safe))); if (archive.type !== "configuration" || !archive.payload?.systemSettings || !archive.payload?.ai) throw new Error("הקובץ אינו גיבוי הגדרות תקין"); await updateState((latest) => { latest.systemSettings = archive.payload.systemSettings; latest.ai = archive.payload.ai; addAudit(latest, { userId: currentSession(request)?.userId || null, action: "configuration.imported", target: safe }); return latest; }); return Response.json({ ok: true, imported: safe }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "ייבוא ההגדרות נכשל" }, { status: 400 }); } }
