import { createHash } from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { readFile, readdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";
import { currentSession, requireAdmin } from "@/server/auth.js";
import { requireSameOrigin } from "@/server/security.js";
import { probeStorage } from "@/server/storage.js";
import { addAudit, readState, updateState, writeState } from "@/server/store.js";
import { databaseStateEnabled, exportDatabase, restoreDatabase } from "@/server/state-database.js";
import { getDataDir } from "@/server/store.js";
export const runtime = "nodejs";

const FORMAT = "caloreazi-backup-v2";
function digest(value: string | Uint8Array) { return createHash("sha256").update(value).digest("hex"); }
async function backupDir(state: unknown) { return (await probeStorage(state, "backup")).resolved; }
function configurationFrom(state: any) { return { version: state.version, ai: state.ai, systemSettings: state.systemSettings }; }
async function mediaPayload(state: any) { const directory = (await probeStorage(state, "gallery")).resolved; const items = []; let total = 0; for (const name of await readdir(directory)) { const safe = path.basename(name); if (safe !== name) continue; const file = path.join(directory, safe); const info = await stat(file); if (!info.isFile()) continue; total += info.size; if (total > 512 * 1024 * 1024) throw new Error("Full backup media exceeds the 512 MB portable archive limit"); const data = await readFile(file); items.push({ name: safe, size: data.length, sha256: digest(data), base64: data.toString("base64") }); } return items; }
async function createArchive(state: any, type: string) { let payload: any; if (type === "configuration") payload = configurationFrom(state); else if (databaseStateEnabled()) { const temporary = path.join(getDataDir(), `.backup-${crypto.randomUUID()}.dump`); try { await exportDatabase(temporary); const dump = await readFile(temporary); payload = { engine: "postgresql", format: "pg_dump-custom", dumpSha256: digest(dump), dumpBase64: dump.toString("base64"), media: type === "full" ? await mediaPayload(state) : [] }; } finally { await unlink(temporary).catch(() => undefined); } } else payload = { engine: "development-json", state, media: type === "full" ? await mediaPayload(state) : [] }; const serialized = JSON.stringify(payload); return { format: FORMAT, type, createdAt: new Date().toISOString(), schemaVersion: state.version, payloadSha256: digest(serialized), payload }; }
function readArchive(data: Uint8Array) { const archive = JSON.parse(gunzipSync(data).toString("utf8")); if (archive.format !== FORMAT || !["database", "configuration", "full", "safety"].includes(archive.type)) throw new Error("פורמט הגיבוי אינו נתמך"); if (digest(JSON.stringify(archive.payload)) !== archive.payloadSha256) throw new Error("בדיקת השלמות של הגיבוי נכשלה"); return archive; }
async function inspectBackup(dir: string, name: string) { const file = path.join(dir, name); const info = await stat(file); try { const data = await readFile(file); const archive = readArchive(data); return { name, size: info.size, createdAt: archive.createdAt || info.mtime.toISOString(), type: archive.type, verified: true, sha256: digest(data) }; } catch (error) { return { name, size: info.size, createdAt: info.mtime.toISOString(), type: "unknown", verified: false, error: error instanceof Error ? error.message : "invalid" }; } }
async function listBackups(state: unknown) { const dir = await backupDir(state); const files = (await readdir(dir)).filter((name) => /^caloreazi-.*\.json\.gz$/.test(name)); return Promise.all(files.map((name) => inspectBackup(dir, name))); }

export async function GET(request: Request) { const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; const requested = new URL(request.url).searchParams.get("download"); if (requested) { const safe = path.basename(requested); if (safe !== requested || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const data = await readFile(path.join(await backupDir(state), safe)); readArchive(data); return new Response(data, { headers: { "Content-Type": "application/gzip", "Content-Disposition": `attachment; filename="${safe}"` } }); } catch { return Response.json({ error: "הגיבוי לא נמצא או אינו תקין" }, { status: 404 }); } } return Response.json({ backups: (await listBackups(state)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), retention: state.systemSettings.backupRetention }); }

export async function POST(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; let body: any = {}; try { body = await request.json(); } catch { /* UI sends no body */ } const type = ["database", "configuration", "full"].includes(body.type) ? body.type : "database"; const dir = await backupDir(state); const name = `caloreazi-${type}-${new Date().toISOString().replace(/[:.]/g, "-")}.json.gz`; const file = path.join(dir, name); await writeFile(file, gzipSync(JSON.stringify(await createArchive(state, type))), { mode: 0o600 }); const verified = await inspectBackup(dir, name); if (!verified.verified) { await unlink(file); return Response.json({ error: "הגיבוי נוצר אך בדיקת השלמות נכשלה" }, { status: 500 }); } await updateState((latest) => { addAudit(latest, { userId: currentSession(request)?.userId || null, action: "backup.created", target: name, details: `${type}:${verified.sha256}` }); return latest; }); const backups = (await listBackups(state)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); const keep = Number(state.systemSettings.backupRetention || 14); for (const item of backups.slice(keep)) await unlink(path.join(dir, item.name)); return Response.json({ ok: true, backup: verified, backups: backups.slice(0, keep) }); }

export async function PATCH(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const current = await readState(); const denied = requireAdmin(current, request); if (denied) return denied; const { name } = await request.json(); const safe = path.basename(String(name || "")); if (safe !== name || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const dir = await backupDir(current); const archive = readArchive(await readFile(path.join(dir, safe))); if (archive.type === "configuration") throw new Error("יש לייבא גיבוי הגדרות דרך Import Configuration ולא דרך שחזור מלא"); const safetyName = `caloreazi-safety-${new Date().toISOString().replace(/[:.]/g, "-")}.json.gz`; await writeFile(path.join(dir, safetyName), gzipSync(JSON.stringify(await createArchive(current, "safety"))), { mode: 0o600 }); const safety = await inspectBackup(dir, safetyName); if (!safety.verified) throw new Error("Safety Backup לא עבר בדיקת שלמות"); if (archive.payload?.engine === "postgresql") { const dump = Buffer.from(String(archive.payload.dumpBase64 || ""), "base64"); if (digest(dump) !== archive.payload.dumpSha256) throw new Error("Database dump checksum mismatch"); const temporary = path.join(getDataDir(), `.restore-${crypto.randomUUID()}.dump`); try { await writeFile(temporary, dump, { mode: 0o600 }); await restoreDatabase(temporary); } finally { await unlink(temporary).catch(() => undefined); } } else if (archive.payload?.engine === "development-json" && archive.payload.state) await writeState(archive.payload.state); else throw new Error("מבנה גיבוי מסד הנתונים אינו תקין"); if (Array.isArray(archive.payload.media)) { const gallery = (await probeStorage(await readState(), "gallery")).resolved; for (const item of archive.payload.media) { const mediaName = path.basename(String(item.name || "")); const data = Buffer.from(String(item.base64 || ""), "base64"); if (!mediaName || mediaName !== item.name || data.length !== item.size || digest(data) !== item.sha256) throw new Error("Media archive verification failed"); await writeFile(path.join(gallery, mediaName), data, { mode: 0o600 }); } } return Response.json({ ok: true, restored: safe, safetyBackup: safetyName }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "שחזור הגיבוי נכשל" }, { status: 400 }); } }

export async function PUT(request: Request) { const originDenied = requireSameOrigin(request); if (originDenied) return originDenied; const current = await readState(); const denied = requireAdmin(current, request); if (denied) return denied; const { name } = await request.json(); const safe = path.basename(String(name || "")); if (safe !== name || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const archive = readArchive(await readFile(path.join(await backupDir(current), safe))); if (archive.type !== "configuration" || !archive.payload?.systemSettings || !archive.payload?.ai) throw new Error("הקובץ אינו גיבוי הגדרות תקין"); await updateState((latest) => { latest.systemSettings = archive.payload.systemSettings; latest.ai = archive.payload.ai; addAudit(latest, { userId: currentSession(request)?.userId || null, action: "configuration.imported", target: safe }); return latest; }); return Response.json({ ok: true, imported: safe }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "ייבוא ההגדרות נכשל" }, { status: 400 }); } }
