import { mkdir, readFile, readdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { requireAdmin } from "@/server/auth.js";
import { addAudit, getDataDir, readState, updateState } from "@/server/store.js";
export const runtime = "nodejs";

async function backupDir() { const dir = path.join(getDataDir(), "backups"); await mkdir(dir, { recursive: true }); return dir; }
async function listBackups() { const dir = await backupDir(); const files = (await readdir(dir)).filter((name) => /^caloreazi-.*\.json\.gz$/.test(name)); return Promise.all(files.map(async (name) => { const info = await stat(path.join(dir, name)); return { name, size: info.size, createdAt: info.mtime.toISOString(), type: "Database + configuration", verified: info.size > 0 }; })); }

export async function GET(request: Request) { const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; const url = new URL(request.url); const requested = url.searchParams.get("download"); if (requested) { const safe = path.basename(requested); if (safe !== requested || !/^caloreazi-.*\.json\.gz$/.test(safe)) return Response.json({ error: "שם גיבוי לא תקין" }, { status: 400 }); try { const data = await readFile(path.join(await backupDir(), safe)); return new Response(data, { headers: { "Content-Type": "application/gzip", "Content-Disposition": `attachment; filename="${safe}"` } }); } catch { return Response.json({ error: "הגיבוי לא נמצא" }, { status: 404 }); } } return Response.json({ backups: (await listBackups()).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), retention: state.systemSettings.backupRetention }); }
export async function POST(request: Request) { const state = await readState(); const denied = requireAdmin(state, request); if (denied) return denied; const name = `caloreazi-${new Date().toISOString().replace(/[:.]/g, "-")}.json.gz`; await writeFile(path.join(await backupDir(), name), gzipSync(JSON.stringify(state, null, 2)), { mode: 0o600 }); await updateState((latest) => { addAudit(latest, { userId: requireAdmin(latest, request) ? null : state.users.find((user) => user.role === "admin")?.id, action: "backup.created", target: name }); return latest; }); const backups = (await listBackups()).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); for (const item of backups.slice(Number(state.systemSettings.backupRetention || 14))) await unlink(path.join(await backupDir(), item.name)); return Response.json({ ok: true, backup: backups[0], backups: backups.slice(0, Number(state.systemSettings.backupRetention || 14)) }); }
