export type OfflineCapture = { clientId: string; imageDataUrl: string; createdAt: string; attempts?: number; lastError?: string };
export type OfflineMutation = { id: string; url: string; method: string; body: string; createdAt: string; attempts: number; lastError?: string };
export type OfflineQueueItem = { id: string; kind: "capture" | "mutation"; label: string; createdAt: string; attempts: number; lastError?: string };
const DB = "caloreazi-offline"; const CAPTURES = "meal-captures"; const MUTATIONS = "mutations";

function database(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB, 2); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(CAPTURES)) db.createObjectStore(CAPTURES, { keyPath: "clientId" }); if (!db.objectStoreNames.contains(MUTATIONS)) db.createObjectStore(MUTATIONS, { keyPath: "id" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function put(store: string, value: unknown) { const db = await database(); await new Promise<void>((resolve, reject) => { const request = db.transaction(store, "readwrite").objectStore(store).put(value); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); db.close(); }
async function remove(store: string, key: string) { const db = await database(); await new Promise<void>((resolve, reject) => { const request = db.transaction(store, "readwrite").objectStore(store).delete(key); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); db.close(); }
async function all<T>(store: string) { const db = await database(); const values = await new Promise<T[]>((resolve, reject) => { const request = db.transaction(store).objectStore(store).getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); db.close(); return values; }
async function count(store: string) { const db = await database(); const value = await new Promise<number>((resolve, reject) => { const request = db.transaction(store).objectStore(store).count(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); db.close(); return value; }

function mutationLabel(url: string) { if (url.includes("/meals")) return "ארוחה"; if (url.includes("/water")) return "שתייה"; if (url.includes("/measurements")) return "מדידת משקל"; if (url.includes("/activity")) return "פעילות"; if (url.includes("/profile")) return "פרטים אישיים"; return "עדכון"; }

export async function queueOfflineCapture(capture: OfflineCapture) { await put(CAPTURES, { ...capture, attempts: capture.attempts || 0 }); }
export async function queueOfflineMutation(mutation: Omit<OfflineMutation, "attempts">) { await put(MUTATIONS, { ...mutation, attempts: 0 }); }
export async function offlineCaptureCount() { return count(CAPTURES); }
export async function offlineMutationCount() { return count(MUTATIONS); }
export async function offlinePendingCount() { return (await offlineCaptureCount()) + (await offlineMutationCount()); }
export async function listOfflineQueue(): Promise<OfflineQueueItem[]> { const [captures, mutations] = await Promise.all([all<OfflineCapture>(CAPTURES), all<OfflineMutation>(MUTATIONS)]); return [...captures.map((item) => ({ id: item.clientId, kind: "capture" as const, label: "צילום ארוחה", createdAt: item.createdAt, attempts: item.attempts || 0, lastError: item.lastError })), ...mutations.map((item) => ({ id: item.id, kind: "mutation" as const, label: mutationLabel(item.url), createdAt: item.createdAt, attempts: item.attempts || 0, lastError: item.lastError }))].sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
export async function retryOfflineItem(item: OfflineQueueItem) { if (item.kind === "capture") { const record = (await all<OfflineCapture>(CAPTURES)).find((entry) => entry.clientId === item.id); if (record) await put(CAPTURES, { ...record, attempts: 0, lastError: undefined }); return; } const record = (await all<OfflineMutation>(MUTATIONS)).find((entry) => entry.id === item.id); if (record) await put(MUTATIONS, { ...record, attempts: 0, lastError: undefined }); }
export async function flushOfflineCaptures(send: (capture: OfflineCapture) => Promise<void>) { const captures = (await all<OfflineCapture>(CAPTURES)).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); let sent = 0; for (const capture of captures) { try { await send(capture); await remove(CAPTURES, capture.clientId); sent += 1; } catch (error) { await put(CAPTURES, { ...capture, attempts: (capture.attempts || 0) + 1, lastError: error instanceof Error ? error.message : "sync failed" }); break; } } return sent; }
export async function flushOfflineMutations(send: (mutation: OfflineMutation) => Promise<void>) { const mutations = (await all<OfflineMutation>(MUTATIONS)).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); let sent = 0; for (const mutation of mutations) { try { await send(mutation); await remove(MUTATIONS, mutation.id); sent += 1; } catch (error) { await put(MUTATIONS, { ...mutation, attempts: mutation.attempts + 1, lastError: error instanceof Error ? error.message : "sync failed" }); break; } } return sent; }
